//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleCalculator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleCalculator.Properties.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plus.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to division.
        /// </summary>
        internal static string Div {
            get {
                return ResourceManager.GetString("Div", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value .
        /// </summary>
        internal static string FinalVal1 {
            get {
                return ResourceManager.GetString("FinalVal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  the value .
        /// </summary>
        internal static string FinalVal2 {
            get {
                return ResourceManager.GetString("FinalVal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is equal to .
        /// </summary>
        internal static string FinalVal3 {
            get {
                return ResourceManager.GetString("FinalVal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the first number: .
        /// </summary>
        internal static string FirstNum {
            get {
                return ResourceManager.GetString("FirstNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Input.
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Enter a number.
        /// </summary>
        internal static string InvalidNum {
            get {
                return ResourceManager.GetString("InvalidNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to times.
        /// </summary>
        internal static string Mult {
            get {
                return ResourceManager.GetString("Mult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the operator: .
        /// </summary>
        internal static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the second number: .
        /// </summary>
        internal static string SecondNum {
            get {
                return ResourceManager.GetString("SecondNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minus.
        /// </summary>
        internal static string Sub {
            get {
                return ResourceManager.GetString("Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid inputs include: &apos;+&apos;, &apos;-&apos;, &apos;*&apos;, &apos;/&apos;, &apos;addition&apos;, &apos;subtraction&apos;, &apos;multiplication&apos;, &apos;division&apos;.
        /// </summary>
        internal static string ValidOps {
            get {
                return ResourceManager.GetString("ValidOps", resourceCulture);
            }
        }
    }
}
